"""Versioned contracts shared by 3mm Core and Agent."""

from three_mm_protocol.models import (
    PROTOCOL_VERSION,
    AgentHealth,
    AgentHeartbeat,
    AgentCommand,
    AgentCommandResult,
    AgentReportedState,
    DeviceDesiredState,
    AgentHello,
    AgentInventory,
    AgentRole,
)
from three_mm_protocol.extension_distribution import (
    MAX_EXTENSION_PACKAGE_BYTES,
    ExtensionArtifactSignatureV1,
    ExtensionArtifactV1,
    ExtensionPublisherKeyV1,
    canonical_extension_artifact_signature,
    verify_extension_artifact_bytes,
    verify_extension_artifact_signature,
)
from three_mm_protocol.module_manifest import (
    EXTENSION_API_VERSION,
    ModuleCapabilities,
    ModuleCompatibility,
    ModuleHealthCheck,
    ModuleManifestV2,
    ModulePublisher,
    ModuleRegistration,
    meets_minimum_version,
    module_compatibility_issues,
    supports_extension_api,
)
from three_mm_protocol.automation import (
    AutomationCapabilityContextV1,
    AutomationCapabilityContextV2,
    AutomationDefinitionV1,
    AutomationValidationIssue,
    CapabilityCommandAction,
    CapabilityContextEntry,
    ProviderCapabilityContextEntry,
    CapabilityEventTrigger,
    validate_automation_capabilities,
)
from three_mm_protocol.runtime_extension import (
    LocalizedTextV1,
    RuntimeEntityV1,
    RuntimeExtensionV1,
    RuntimeFieldV1,
    RuntimeNavigationItemV1,
    RuntimePageV1,
)
from three_mm_protocol.compiled_extension import (
    CompiledUiEntrypointV1,
    CompiledUiExtensionV1,
)
from three_mm_protocol.theme_extension import ThemeExtensionV1, ThemeTokensV1
from three_mm_protocol.capability_builder import (
    BuilderSettingV1,
    CapabilityBindingV1,
    CapabilityPlanV1,
    CapabilityPresentationV1,
    PresentationStateV1,
)
from three_mm_protocol.capability_state import (
    CapabilityStateReportV1,
    CapabilityStateSnapshotV1,
)
from three_mm_protocol.device_inventory import DeviceInventoryV2
from three_mm_protocol.device_event import DeviceEventV1
from three_mm_protocol.node_features import (
    CoreNodeProtocolV1,
    DeviceRuntimeFeaturesV1,
    DeviceRuntimeFeaturesReportV1,
    DeviceRuntimeFeaturesSnapshotV1,
)
from three_mm_protocol.device_capabilities import (
    CapabilityAdvertisementV1,
    CapabilityProviderReportV1,
    CapabilityProviderSnapshotV1,
    CapabilityProviderControlV1,
    CapabilityRegistrationV2,
)
from three_mm_protocol.capability_contracts import CapabilityContractV1, CapabilityActionV1
from three_mm_protocol.identifier_scan import (
    IdentifierScanEventV1,
    IdentifierScanPayloadV1,
)
from three_mm_protocol.backup import (
    BACKUP_MANIFEST_VERSION,
    BackupCompatibilityV1,
    BackupEntryV1,
    BackupManifestV1,
    BackupProtectionV1,
)
from three_mm_protocol.application_extension import (
    ApplicationConnectorV1,
    ApplicationEventSubscriptionV1,
    ApplicationExtensionV1,
    ApplicationJobV1,
    ApplicationLifecycleV1,
    ApplicationOperationV1,
    ApplicationPermissionV1,
    ApplicationPublicHttpRequestV1,
    ApplicationPublicHttpResponseV1,
    ApplicationPublicHttpRouteV1,
    ApplicationRouteV1,
    ApplicationServiceV1,
    ApplicationStorageV1,
    public_http_request_schema_v1,
    public_http_response_schema_v1,
)

__all__ = [
    "PROTOCOL_VERSION",
    "MAX_EXTENSION_PACKAGE_BYTES",
    "ExtensionArtifactSignatureV1",
    "ExtensionArtifactV1",
    "ExtensionPublisherKeyV1",
    "canonical_extension_artifact_signature",
    "verify_extension_artifact_bytes",
    "verify_extension_artifact_signature",
    "AgentHealth",
    "AgentHeartbeat",
    "AgentCommand",
    "AgentCommandResult",
    "AgentReportedState",
    "DeviceDesiredState",
    "AgentHello",
    "AgentInventory",
    "DeviceInventoryV2",
    "DeviceEventV1",
    "CoreNodeProtocolV1",
    "DeviceRuntimeFeaturesV1",
    "DeviceRuntimeFeaturesReportV1",
    "DeviceRuntimeFeaturesSnapshotV1",
    "CapabilityAdvertisementV1",
    "CapabilityProviderReportV1",
    "CapabilityProviderSnapshotV1",
    "CapabilityProviderControlV1",
    "CapabilityRegistrationV2",
    "CapabilityContractV1",
    "CapabilityActionV1",
    "AgentRole",
    "EXTENSION_API_VERSION",
    "ModuleCapabilities",
    "ModuleCompatibility",
    "ModuleHealthCheck",
    "ModuleManifestV2",
    "ModulePublisher",
    "ModuleRegistration",
    "meets_minimum_version",
    "module_compatibility_issues",
    "supports_extension_api",
    "AutomationCapabilityContextV1",
    "AutomationCapabilityContextV2",
    "AutomationDefinitionV1",
    "AutomationValidationIssue",
    "CapabilityCommandAction",
    "CapabilityContextEntry",
    "ProviderCapabilityContextEntry",
    "CapabilityEventTrigger",
    "validate_automation_capabilities",
    "LocalizedTextV1",
    "RuntimeEntityV1",
    "RuntimeExtensionV1",
    "RuntimeFieldV1",
    "RuntimeNavigationItemV1",
    "RuntimePageV1",
    "CompiledUiEntrypointV1",
    "CompiledUiExtensionV1",
    "ThemeExtensionV1",
    "ThemeTokensV1",
    "BuilderSettingV1",
    "CapabilityBindingV1",
    "CapabilityPlanV1",
    "CapabilityPresentationV1",
    "PresentationStateV1",
    "CapabilityStateReportV1",
    "CapabilityStateSnapshotV1",
    "IdentifierScanEventV1",
    "IdentifierScanPayloadV1",
    "BACKUP_MANIFEST_VERSION",
    "BackupCompatibilityV1",
    "BackupEntryV1",
    "BackupManifestV1",
    "BackupProtectionV1",
    "ApplicationConnectorV1",
    "ApplicationEventSubscriptionV1",
    "ApplicationExtensionV1",
    "ApplicationJobV1",
    "ApplicationLifecycleV1",
    "ApplicationOperationV1",
    "ApplicationPermissionV1",
    "ApplicationPublicHttpRequestV1",
    "ApplicationPublicHttpResponseV1",
    "ApplicationPublicHttpRouteV1",
    "ApplicationRouteV1",
    "ApplicationServiceV1",
    "ApplicationStorageV1",
    "public_http_request_schema_v1",
    "public_http_response_schema_v1",
]
