import { useI18n } from '@/utils/i18n'

const en = {
  manage: 'Application access', title: 'Application resource access', close: 'Close', refresh: 'Refresh status',
  help: 'Service access to devices, events and external APIs. User roles and application access remain separate.',
  events: 'Device event subscriptions',
  publications: 'Application event publications',
  nativeOnly: 'Reviewed native code only — not a sandbox. Code trust must be recorded locally for this exact package; this screen cannot create it.',
  compatibility: 'Compatibility mode', review_required: 'New review required', enforced: 'Reviewed access mode',
  compatAccess: 'Existing compatibility access unchanged',
  effective: 'Current rights are effective', inactive: 'Rights saved, application stopped', stale: 'No current effective rights',
  digest: 'Installed package · SHA-256', nativeReview: 'Local code review', chooseReview: 'Choose a verified local review',
  noNative: 'No current local code review is available. A trusted reviewer must review this exact code and record it with Core local administration before continuing.',
  adoption: 'First adoption requires a verified recoverable backup and a stopped application. Close this screen and disable the application first. Nothing is stopped automatically.',
  adoptionReady: 'The application is stopped. Verify a recoverable backup before first adoption. Re-enable invalidates these rights and requires a fresh review after start.',
  create: 'Review requested access', review: 'Exact access to approve', resources: 'Devices and external APIs', commands: 'Device commands', connectors: 'External API connectors',
  fullBindings: 'All listed bindings are required in this first profile. No wider rights or automatic wildcard access are granted.',
  acknowledge: 'I have reviewed these exact resources and limits.', approve: 'Approve review', apply: 'Apply rights', deny: 'Deny review',
  pending: 'Approved, not applied. Current rights have not changed.', applied: 'Rights applied. Check the current status below; stopped applications cannot perform actions.',
  denied: 'Review denied. Existing rights were not changed.', revoked: 'Rights revoked. Already admitted actions cannot be recalled and will not be replayed.',
  expires: 'Review expires in', seconds: 'seconds', expired: 'This review expired. Refresh and create a new review; old approval cannot be reused.',
  revoke: 'Revoke rights', revokeTitle: 'Stop new authorized actions?',
  revokeHelp: 'New commands, event deliveries and API requests will be denied. Already admitted actions may still finish. Application data and historical outcomes are preserved.',
  confirmRevoke: 'Confirm revocation', cancel: 'Cancel', loading: 'Reading current authority…',
  uncertain: 'The result could not be confirmed. No automatic retry was sent. Refresh status and create a fresh review if needed.',
  staleReview: 'The package, resources or review changed. Refresh status and review the current resources again.',
  actor: 'A current administrator login is required. Log in again before changing rights.',
  unsupported: 'This application is not supported by the current headless command/connector/event adapter. Its existing compatibility behavior is unchanged.',
  unavailable: 'Authority could not be read. Check the Core review key, installed package and recovery state, then refresh. No fallback permissions were enabled.',
  noGrant: 'No current rights can be revoked here. Refresh or create a new supported review.',
  empty: 'No resource bindings declared.',
} as const
const bg: Record<keyof typeof en, string> = {
  manage: 'Права на приложението', title: 'Достъп на приложението до ресурси', close: 'Затвори', refresh: 'Обнови статуса',
  help: 'Достъп на службата до устройства, събития и външни API. Потребителските роли и достъпът до приложението са отделни.',
  events: 'Абонаменти за събития от устройства',
  publications: 'Публикуване на събития от приложението',
  nativeOnly: 'Само локално прегледан код — не е sandbox. Доверието към точно този пакет се записва локално; този екран не може да го създава.',
  compatibility: 'Съвместим режим', review_required: 'Нужен е нов преглед', enforced: 'Режим с прегледани права',
  compatAccess: 'Старият съвместим достъп не е променен',
  effective: 'Текущите права са в сила', inactive: 'Правата са записани, приложението е спряно', stale: 'Няма текущи действащи права',
  digest: 'Инсталиран пакет · SHA-256', nativeReview: 'Локален преглед на кода', chooseReview: 'Избери проверен локален преглед',
  noNative: 'Няма валиден локален преглед. Доверен човек трябва да прегледа точно този код и да запише прегледа чрез локалното управление на Core.',
  adoption: 'Първото преминаване изисква проверен възстановим бекъп и спряно приложение. Затвори екрана и първо изключи приложението. Нищо не се спира автоматично.',
  adoptionReady: 'Приложението е спряно. Провери възстановим бекъп преди първото преминаване. Повторното включване отменя валидността на тези права и изисква нов преглед след старта.',
  create: 'Прегледай заявения достъп', review: 'Точен достъп за одобрение', resources: 'Устройства и външни API', commands: 'Команди към устройства', connectors: 'Връзки към външни API',
  fullBindings: 'Всички изброени връзки са задължителни в този първи профил. Не се дават по-широки права или неограничен достъп.',
  acknowledge: 'Прегледах точно тези ресурси и ограничения.', approve: 'Одобри прегледа', apply: 'Приложи правата', deny: 'Откажи прегледа',
  pending: 'Одобрено, но не е приложено. Текущите права не са променени.', applied: 'Правата са приложени. Провери текущия статус отдолу; спряното приложение не може да извършва действия.',
  denied: 'Прегледът е отказан. Старите права не са променени.', revoked: 'Правата са отнети. Вече допуснати действия не могат да бъдат върнати назад и няма да се повтарят.',
  expires: 'Прегледът изтича след', seconds: 'секунди', expired: 'Прегледът е изтекъл. Обнови и създай нов; старото одобрение не може да се използва отново.',
  revoke: 'Отнеми правата', revokeTitle: 'Да блокираме ли новите действия?',
  revokeHelp: 'Нови команди, доставки на събития и API заявки ще бъдат отказвани. Вече допуснати действия може да завършат. Данните и историята на приложението се запазват.',
  confirmRevoke: 'Потвърди отнемането', cancel: 'Отказ', loading: 'Проверка на текущите права…',
  uncertain: 'Резултатът не може да се потвърди. Няма автоматичен повторен опит. Обнови статуса и при нужда създай нов преглед.',
  staleReview: 'Пакетът, ресурсите или прегледът са променени. Обнови статуса и прегледай актуалните ресурси.',
  actor: 'Нужна е текуща администраторска сесия. Влез отново, преди да променяш правата.',
  unsupported: 'Това приложение не се поддържа от текущия адаптер за приложения без собствен интерфейс, с команди, събития и API връзки. Старият съвместим режим не се променя.',
  unavailable: 'Правата не могат да се прочетат. Провери ключа за прегледи в Core, инсталирания пакет и състоянието след възстановяване. Няма включени резервни разрешения.',
  noGrant: 'Тук няма текущи права за отнемане. Обнови или създай нов поддържан преглед.',
  empty: 'Няма заявени връзки към ресурси.',
}
export type AuthorityLabel = keyof typeof en
export function useAuthorityLabels() {
  const { t, currentLanguage } = useI18n()
  return (key: AuthorityLabel) => t(`applicationAuthority.${key}`, (currentLanguage.value === 'bg' ? bg : en)[key])
}
