import { useI18n } from './i18n'

const en = {
  navigation: 'Navigation', openMenu: 'Open navigation', closeMenu: 'Close navigation', skip: 'Skip to content',
  language: 'Language', search: 'Search commands', recovery: 'Built-in appearance recovery',
  preview: 'Appearance preview', previewNote: 'Browser-only preview. Nothing is saved to the installation.',
  exit: 'Back to Settings', restore: 'Restore built-in preview', recoveryNote: 'The preview has been cleared. Your installed theme and saved settings are unchanged.',
  restoreInstalled: 'Use built-in permanently', restoreFailed: 'Could not change the theme. Please retry.', restoreDone: 'Built-in selected. Saved settings are preserved.',
  layout: 'Navigation layout', sidebar: 'Sidebar', top: 'Top navigation', density: 'Density',
  compact: 'Compact', comfortable: 'Comfortable', header: 'Use theme header colors',
  buttons: 'Button style', solid: 'Solid', outline: 'Outline', cards: 'Card style', bordered: 'Bordered', raised: 'Raised',
  mode: 'Color mode', light: 'Light', dark: 'Dark', primitives: 'Shared controls',
  primary: 'Primary action', secondary: 'Secondary action', danger: 'Danger action', disabled: 'Disabled', loading: 'Loading',
  forms: 'Form controls', name: 'Name', namePlaceholder: 'A clear, descriptive name',
  description: 'Description', descriptionPlaceholder: 'Optional details', error: 'Please enter a name.',
  enabled: 'Enable this example', enabledHelp: 'Demonstration only — no hardware or application operations.',
  dialog: 'Open test dialog', dialogTitle: 'Review example settings', cancel: 'Cancel', confirm: 'Validate example',
  close: 'Close', ready: 'Ready', pending: 'Pending', status: 'Status', resource: 'Resource', owner: 'Owner',
  table: 'Table and status', example: 'Example resource with a longer label', currentUser: 'Current user',
  validated: 'Example validated. No data was saved.', preferences: 'Preview controls',
  appearanceTitle: 'Layout and appearance',
  appearanceHelp: 'Preview changes here, then save for this installation. Each theme version keeps its own settings; the ZIP package is unchanged.',
  customHeader: 'Use custom header colors', headerBackground: 'Header background color', headerText: 'Header text color',
  headerContrast: 'Choose valid colors with readable text (contrast at least 4.5:1).',
  modeHelp: 'Light/dark mode is your personal preference, saved immediately. It does not change the installation for other users.',
  saveAppearance: 'Save appearance', discardAppearance: 'Discard changes', resetAppearance: 'Use theme defaults',
  unsavedAppearance: 'Unsaved preview — leaving this section discards your changes.',
  saveAppearanceFailed: 'Could not save. Refresh the theme and try again; your changes remain unsaved.',
  appearanceSaved: 'Appearance saved.', appearanceReset: 'Theme defaults restored. Branding and custom colors are preserved.',
  componentPreview: 'Open component preview', branding: 'Branding',
  brandingHelp: 'Site name and header message are translated per language. Your logo applies to every language. Visual settings are in Theme Customization.',
} as const
const bg: Record<keyof typeof en, string> = {
  navigation: 'Навигация', openMenu: 'Отвори навигацията', closeMenu: 'Затвори навигацията', skip: 'Към съдържанието',
  language: 'Език', search: 'Търси команди', recovery: 'Връщане към вградения изглед',
  preview: 'Преглед на оформлението', previewNote: 'Временен преглед в този браузър. Нищо не се записва в инсталацията.',
  exit: 'Назад към Настройки', restore: 'Възстанови вградения преглед', recoveryNote: 'Прегледът е изчистен. Инсталираната тема и запазените настройки не са променени.',
  restoreInstalled: 'Използвай вградената тема постоянно', restoreFailed: 'Темата не може да се промени. Опитай отново.', restoreDone: 'Избрана е вградената тема. Запазените настройки са съхранени.',
  layout: 'Разположение на навигацията', sidebar: 'Странична лента', top: 'Горна навигация', density: 'Плътност',
  compact: 'Компактна', comfortable: 'Свободна', header: 'Използвай цветовете на темата за хедъра',
  buttons: 'Стил на бутоните', solid: 'Плътни', outline: 'Контурни', cards: 'Стил на картите', bordered: 'С рамка', raised: 'Със сянка',
  mode: 'Цветови режим', light: 'Светъл', dark: 'Тъмен', primitives: 'Общи контроли',
  primary: 'Основно действие', secondary: 'Вторично действие', danger: 'Опасно действие', disabled: 'Неактивно', loading: 'Зареждане',
  forms: 'Полета на формата', name: 'Име', namePlaceholder: 'Ясно и описателно име',
  description: 'Описание', descriptionPlaceholder: 'Допълнителни подробности', error: 'Моля, въведи име.',
  enabled: 'Включи този пример', enabledHelp: 'Само демонстрация — без операции с хардуер или приложения.',
  dialog: 'Отвори тестов диалог', dialogTitle: 'Преглед на примерните настройки', cancel: 'Отказ', confirm: 'Провери примера',
  close: 'Затвори', ready: 'Готово', pending: 'Изчаква', status: 'Статус', resource: 'Ресурс', owner: 'Собственик',
  table: 'Таблица и статус', example: 'Примерен ресурс с по-дълъг етикет', currentUser: 'Текущ потребител',
  validated: 'Примерът е проверен. Няма записани данни.', preferences: 'Контроли за прегледа',
  appearanceTitle: 'Оформление и външен вид',
  appearanceHelp: 'Пробвай промените тук и ги запази за тази инсталация. Всяка версия на тема пази свои настройки; ZIP пакетът не се променя.',
  customHeader: 'Използвай собствени цветове за хедъра', headerBackground: 'Цвят на фона на хедъра', headerText: 'Цвят на текста в хедъра',
  headerContrast: 'Избери валидни цветове с четим текст (контраст поне 4.5:1).',
  modeHelp: 'Светъл/тъмен режим е лична настройка и се записва веднага. Не променя изгледа за другите потребители.',
  saveAppearance: 'Запази оформлението', discardAppearance: 'Откажи промените', resetAppearance: 'Настройки на темата',
  unsavedAppearance: 'Незаписан преглед — напускането на тази секция отменя промените.',
  saveAppearanceFailed: 'Записът не успя. Обнови темата и опитай отново; промените остават незаписани.',
  appearanceSaved: 'Оформлението е запазено.', appearanceReset: 'Настройките на темата са възстановени. Логото, текстовете и старите цветове са запазени.',
  componentPreview: 'Отвори преглед на компонентите', branding: 'Идентичност',
  brandingHelp: 'Името и съобщението се превеждат по езици. Логото е общо за всички езици. Визуалните настройки са в Персонализиране на тема.',
}
export function useUiLabels() {
  const { t, currentLanguage } = useI18n()
  return (key: keyof typeof en) => t(`uiPlatform.${key}`, (currentLanguage.value === 'bg' ? bg : en)[key])
}
